(define (square x) (* x x))
(define (sum-of-squares x y) (+ (square x) (square y)))

(define (proc x y z) 
    (if (> x y)
        (if (> z y)
            (sum-of-squares x z)
            (sum-of-squares x y))
        (if (> x z)
            (sum-of-squares x y)
            (sum-of-squares y z)
        )
    )   
)