(define (square x) (* x x))
(define (sum-of-squares x y) (+ (square x) (square y)))

(define (ex x y z) 
    (if (> x y)
        (if (> z y)
            (sum-of-squares x z)
            (sum-of-squares x y)
        )
        (if (> z x)
            (sum-of-squares y z)
            (sum-of-squares x y)
        )
    )   
)